# Generated by Django 5.0.6 on 2024-07-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='tags',
            field=models.ManyToManyField(blank=True, to='yearbook.tag'),
        ),
    ]
